[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.5.0"
lazy_static = { features = ["spin_no_std"], version = "1.5.0" }
log = "0.4.27"
spin = "0.10.0"
x86_64 = "0.15.2"

[profile.dev]
panic = "abort"
debug = true
split-debuginfo = "packed"
