[build]
target = ".cargo/target.json"

rustflags = [
    "-C", "link-arg=/base:0xffffffff80000000",
    "-C", "link-arg=/subsystem:console",
    "-C", "link-arg=/entry:kmain",
    "-C", "link-arg=/opt:noref",
    "-C", "link-arg=/pdb:./target/target/debug/kernel.pdb",
]